services:
  peekaping:
    build:
      context: .
      dockerfile: Dockerfile.bundle.postgres
    restart: always
    ports:
      - "8383:8383"
    env_file:
      - .env
    environment:
      - DB_TYPE=postgres
      - DB_HOST=localhost
      - DB_PASS=${DB_PASS}
      - DB_PORT=5432
      - QUEUE_CONCURRENCY=${QUEUE_CONCURRENCY}
      - TZ=${TZ}
      - LOG_LEVEL=error
    volumes:
      - peekaping_pg_data:/var/lib/postgresql/data
      - peekaping_logs:/var/log/supervisor
    container_name: peekaping-bundle-postgres
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3" 
volumes:
  peekaping_pg_data:
  peekaping_logs:
